document.addEventListener("DOMContentLoaded", () => {
    console.log("Script de máquinas cargado correctamente")
  
    // Base de datos de máquinas completadas
    const maquinasDB = [
      {
        id: 1,
        nombre: "Cat",
        plataforma: "hackthebox",
        dificultad: "Medium",
        os: "Linux",
        ip: "10.10.10.3",
        fecha: "2023-01-15",
        categorias: ["smb", "privesc"],
        enlace: "https://app.hackthebox.com/machines/Cat",
      },
      {
        id: 2,
        nombre: "Rabbit",
        plataforma: "hackthebox",
        dificultad: "Insane",
        os: "Windows",
        ip: "10.10.10.71",
        fecha: "2023-01-20",
        categorias: ["Payload creation", "SQL injection"],
        enlace: "https://app.hackthebox.com/machines/Rabbit",
      },
      {
        id: 3,
        nombre: "Blackfield",
        plataforma: "hackthebox",
        dificultad: "Hard",
        os: "Windows",
        ip: "10.10.10.4",
        fecha: "2023-01-25",
        categorias: ["smb", "ms08-067"],
        enlace: "https://app.hackthebox.com/machines/Blackfield",
      },
      {
        id: 4,
        nombre: "RootMe",
        plataforma: "tryhackme",
        dificultad: "Easy",
        os: "Linux",
        ip: "10.10.10.108",
        fecha: "2023-02-05",
        categorias: ["web", "privesc", "php"],
        enlace: "https://tryhackme.com/room/rootme",
      },
      {
        id: 5,
        nombre: "Vulnversity",
        plataforma: "tryhackme",
        dificultad: "Easy",
        os: "Linux",
        ip: "10.10.10.109",
        fecha: "2023-02-10",
        categorias: ["web", "privesc", "upload"],
        enlace: "https://tryhackme.com/room/vulnversity",
      },
      {
        id: 6,
        nombre: "Metasploitable 2",
        plataforma: "vulnhub",
        dificultad: "Easy",
        os: "Linux",
        ip: "192.168.1.100",
        fecha: "2023-02-15",
        categorias: ["metasploit", "multiple"],
        enlace: "https://www.vulnhub.com/entry/metasploitable-2,29/",
      },
      {
        id: 7,
        nombre: "Nibbles",
        plataforma: "hackthebox",
        dificultad: "Easy",
        os: "Linux",
        ip: "10.10.10.75",
        fecha: "2023-02-20",
        categorias: ["web", "privesc", "cms"],
        enlace: "https://app.hackthebox.com/machines/Nibbles",
      },
      {
        id: 8,
        nombre: "Beep",
        plataforma: "hackthebox",
        dificultad: "Easy",
        os: "Linux",
        ip: "10.10.10.7",
